version: '3.7'
services:
  web:
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    command: flask run --host=0.0.0.0 --port=5001
    volumes:
      - './:/app'
    ports:
      - '5000:5001'
